CREATE TABLE IF NOT EXISTS Supplier(
SupplierID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
SupplierName TEXT NOT NULL,
SupplierAddress TEXT NOT NULL,
SupplierEmail TEXT NOT NULL,
SupplierPhone TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS Category(
CategoryID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
CategoryName TEXT NOT NULL,
IconID INTEGER);

CREATE TABLE IF NOT EXISTS Product(
ProductID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
CategoryID INTEGER NOT NULL,
ProductName TEXT NOT NULL,
SalePrice REAL NOT NULL,
Quantity INTEGER NOT NULL,
QuantityUnit TEXT NOT NULL,
SupplierID INTEGER NOT NULL,
PicID INTEGER,
FOREIGN KEY(CategoryID) REFERENCES Category(CategoryID) ON DELETE SET NULL,
FOREIGN KEY(SupplierID) REFERENCES Supplier(SupplierID) ON DELETE SET NULL );