INSERT INTO Supplier (SupplierName, SupplierAddress, SupplierEmail, SupplierPhone) VALUES ('Ace Meats Ltd.','13 Road Drive, Sandyland, Co. Dublin','supplies@acemeats.com','01-236-9985');
INSERT INTO Supplier (SupplierName, SupplierAddress, SupplierEmail, SupplierPhone) VALUES ('McFallon Fruit Supplies','19 Grange Terrace, Farmtown, Co. Dublin','orders@mfss.ie','01-295-7386');
INSERT INTO Supplier (SupplierName, SupplierAddress, SupplierEmail, SupplierPhone) VALUES ('Grange Dairies','22A Parkway, Cintertown, Co. Dublin','suppliers@grangedairies.com','01-240-6325');
INSERT INTO Supplier (SupplierName, SupplierAddress, SupplierEmail, SupplierPhone) VALUES ('Fresh Farms Inc.','Building 4, Citadel Business Park, Chipstown, Co. Dublin','inquiries@ffi.ie','01-236-9986');
INSERT INTO Supplier (SupplierName, SupplierAddress, SupplierEmail, SupplierPhone) VALUES ('Sulvihill Foods Ltd.','Unit 7, Langstown Business Centre, Grangeland, Co. Dublin','orders@sulbihill.ie','01-296-1120');
INSERT INTO Supplier (SupplierName, SupplierAddress, SupplierEmail, SupplierPhone) VALUES ('Baker''s Pantry','32 Tent Street, Tindale, Co. Dublin','supply@bakerspantry.com','01-395-7351');
INSERT INTO Supplier (SupplierName, SupplierAddress, SupplierEmail, SupplierPhone) VALUES ('Parvo International','Unit 100-105, Langstown Business Centre, Grangeland, Co. Dublin','ieorders@parvoint.com','01-136-1230');
INSERT INTO Supplier (SupplierName, SupplierAddress, SupplierEmail, SupplierPhone) VALUES ('Citcon Food Suppliers','Building 9, Citadel Business Park, Chipstown, Co. Dublin','foodsupplies@citcon.com','01-295-7389');

INSERT INTO Category (CategoryName, IconID) VALUES ('Bakery','bakery');
INSERT INTO Category (CategoryName, IconID) VALUES ('Cereals & Dried Foods','cereal');
INSERT INTO Category (CategoryName, IconID) VALUES ('Dairy, Milk & Eggs','dairy');
INSERT INTO Category (CategoryName, IconID) VALUES ('Deli','deli');
INSERT INTO Category (CategoryName, IconID) VALUES ('Drinks','drinks');
INSERT INTO Category (CategoryName, IconID) VALUES ('Frozen Foods','freezer');
INSERT INTO Category (CategoryName, IconID) VALUES ('Fruit & Vegetables','butcher');
INSERT INTO Category (CategoryName, IconID) VALUES ('Herbs & Spices','butcher');
INSERT INTO Category (CategoryName, IconID) VALUES ('Home Baking','baking');
INSERT INTO Category (CategoryName, IconID) VALUES ('Meat & Poultry','butcher');
INSERT INTO Category (CategoryName, IconID) VALUES ('Nuts, Seeds & Dried Fruit','nuts');
INSERT INTO Category (CategoryName, IconID) VALUES ('Oils','oils');
INSERT INTO Category (CategoryName, IconID) VALUES ('Seafood','seafood');
INSERT INTO Category (CategoryName, IconID) VALUES ('Sweets & Snacks','sweets');
INSERT INTO Category (CategoryName, IconID) VALUES ('Vitamins & Supplements','vitamin');

INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Red Apples',7,3.24639,26,'kg',2,'android.resource://com.example.android.productmanager/drawable/apple_red');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Bananas',7,2.22204,19,'kg',2,'android.resource://com.example.android.productmanager/drawable/banana');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Broccoli',7,2.0608,26,'kg',4,'android.resource://com.example.android.productmanager/drawable/broccoli');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('McCambridges Brown Soda Bread (500g)',1,4.38522,21,'pack(s)',6,'android.resource://com.example.android.productmanager/drawable/brown_soda_bread_mccambridge_500g');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Red Cabbage',7,2.70759,16,'kg',4,'android.resource://com.example.android.productmanager/drawable/cabbage_red');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Carrots',7,3.48142,10,'kg',4,'android.resource://com.example.android.productmanager/drawable/carrots');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Cauliflower',7,3.61968,2,'kg',4,'android.resource://com.example.android.productmanager/drawable/cauliflower');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Courgette',7,3.59497,2,'kg',5,'android.resource://com.example.android.productmanager/drawable/courgette');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Irish Pride Farmhouse Soda Bread (460g)',1,3.6386,23,'pack(s)',6,'android.resource://com.example.android.productmanager/drawable/farmhouse_soda_irish_pride_460g');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Red Grapefruit',7,4.62021,8,'kg',7,'android.resource://com.example.android.productmanager/drawable/grapefruit_red');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Leeks',7,4.56777,19,'kg',5,'android.resource://com.example.android.productmanager/drawable/leeks');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Lemons',7,3.10764,23,'kg',4,'android.resource://com.example.android.productmanager/drawable/lemons');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Limes',7,2.07573,11,'kg',7,'android.resource://com.example.android.productmanager/drawable/limes');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Cantaloupe Melons',7,3.11792,29,'kg',4,'android.resource://com.example.android.productmanager/drawable/melon_cantaloupe');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Gala Melons',7,1.70288,18,'kg',5,'android.resource://com.example.android.productmanager/drawable/melon_gala');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Yellow Melons',7,3.2663,4,'kg',7,'android.resource://com.example.android.productmanager/drawable/melon_yellow');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Pat''s Multiseed Bread (700g)',1,2.64458,2,'pack(s)',4,'android.resource://com.example.android.productmanager/drawable/multiseed_bread_700g');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Red Onions',7,3.50904,12,'kg',4,'android.resource://com.example.android.productmanager/drawable/onion_red');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('White Onions',7,3.85808,20,'kg',5,'android.resource://com.example.android.productmanager/drawable/onion_white');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Oranges',7,2.48303,19,'kg',4,'android.resource://com.example.android.productmanager/drawable/orange');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Parsnips',7,2.98256,10,'kg',5,'android.resource://com.example.android.productmanager/drawable/parsnips');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Pears',7,1.58553,6,'kg',4,'android.resource://com.example.android.productmanager/drawable/pear');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Green Peppers',7,1.40688,12,'kg',5,'android.resource://com.example.android.productmanager/drawable/pepper_green');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Red Peppers',7,3.18166,8,'kg',4,'android.resource://com.example.android.productmanager/drawable/pepper_red');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Yellow Peppers',7,2.37039,18,'kg',5,'android.resource://com.example.android.productmanager/drawable/pepper_yellow');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Rhubarb',7,1.7233,3,'kg',8,'android.resource://com.example.android.productmanager/drawable/rhubarb');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Turnips',7,2.96103,10,'kg',8,'android.resource://com.example.android.productmanager/drawable/turnip');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('McCambridges Spelt Bread (500g)',1,1.61216,20,'pack(s)',6,'android.resource://com.example.android.productmanager/drawable/spelt_bread_mccambridges_500g');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Round Roast Beef',10,5.99,28,'kg',8,'android.resource://com.example.android.productmanager/drawable/beef_round_roast');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Rib Eye Steak',10,25,13,'kg',1,'android.resource://com.example.android.productmanager/drawable/steak_rib_eye');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Striploin Steak',10,22,3,'kg',1,'android.resource://com.example.android.productmanager/drawable/steak_striploin');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Chicken Oyster Thighs',10,2.3335,24,'kg',8,'android.resource://com.example.android.productmanager/drawable/chicken_thighs');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Chicken Drumsticks',10,2.91418,30,'kg',8,'android.resource://com.example.android.productmanager/drawable/chicken_drumsticks');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Lamb Cutlets',10,4.27346,28,'kg',8,'android.resource://com.example.android.productmanager/drawable/lamb_cutlets');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Lamb Leg',10,4.34887,7,'kg',1,'android.resource://com.example.android.productmanager/drawable/lamb_leg');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Pork Loin Chops',10,2.68095,9,'kg',8,'android.resource://com.example.android.productmanager/drawable/pork_chops');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Sea Bass Fillets',13,10.32,6,'kg',7,'android.resource://com.example.android.productmanager/drawable/sea_bass_fillets');
INSERT INTO Product (ProductName, CategoryID, SalePrice, Quantity, QuantityUnit, SupplierID, PicID) VALUES ('Hake Fillets',13,1.877,7,'kg',7,'android.resource://com.example.android.productmanager/drawable/hake_fillets');
